---
title: "ONI FE models"
author: "Carles Milà"
date: "2025-07-07"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center",
                      warning = FALSE,
                      message = FALSE)

library("GHRmodel")
library("dplyr")
library("sf")
library("ggplot2")
library("cowplot")

# Env: Local
data <- read.csv("data/processed/weekly_data.csv") 
koppen_labs <- levels(as.factor(data$koppen)); names(koppen_labs) <- 1:length(koppen_labs)
```

# GOF

```{r gof, fig.width=6, fig.height=3}
modgof1 <- read.csv("output/oni_fe/baseline_gof.csv") |> 
  mutate(Model = "Baseline", model_id = "Baseline")  |> 
  select(model_id, dic, waic, lms, mae, Model)
modgof2 <- read.csv("output/oni_fe/linear_gof.csv") |> 
  mutate(Model = "Linear", model_id = paste0("oni.l", 1:6)) |> 
  select(model_id, dic, waic, lms, mae, Model)
modgod3 <- read.csv("output/oni_fe/linear_koppen_gof.csv") |> 
  mutate(Model = "Linear (replicated)", model_id = paste0("oni.l", 1:6)) |> 
  select(model_id, dic, waic, lms, mae, Model)
modgof <- rbind(modgof1, modgof2, modgod3)

# DIC
ggplot(modgof, aes(x = model_id, y = dic, col = Model)) +
  geom_point() +
  geom_hline(yintercept = modgof1$dic, col = "grey40", alpha = 0.4) +
  theme_bw()

# WAIC
ggplot(modgof, aes(x = model_id, y = waic, col = Model)) +
  geom_point() +
  geom_hline(yintercept = modgof1$waic, col = "grey40", alpha = 0.4) +
  theme_bw()

# LMS
ggplot(modgof, aes(x = model_id, y = lms, col = Model)) +
  geom_point() +
  geom_hline(yintercept = modgof1$lms, col = "grey40", alpha = 0.4) +
  theme_bw()

# MAE
ggplot(modgof, aes(x = model_id, y = mae, col = Model)) +
  geom_point() +
  geom_hline(yintercept = modgof1$mae, col = "grey40", alpha = 0.4) +
  theme_bw()
```

# Effects

## Linear

```{r effects linear, fig.width=4, fig.height=4}
mod2 <- readRDS("output/oni_fe/linear_mod.rds")
plot_coef_lin(mod2) + theme(legend.position = "none")
```

## Replicated

```{r effects replicated, fig.width=8, fig.height=6}
mod3 <- readRDS("output/oni_fe/linear_koppen_mod.rds")
p1 <- plot_coef_varying(mod3, 
                        mod_id = "mod1",
                        name = "koppen_id5", 
                        unit_label = koppen_labs) 
p2 <- plot_coef_varying(mod3, 
                        mod_id = "mod2",
                        name = "koppen_id5", 
                        unit_label = koppen_labs) 
p3 <- plot_coef_varying(mod3, 
                        mod_id = "mod3",
                        name = "koppen_id5", 
                        unit_label = koppen_labs)
p4 <- plot_coef_varying(mod3, 
                        mod_id = "mod4",
                        name = "koppen_id5", 
                        unit_label = koppen_labs)
p5 <- plot_coef_varying(mod3, 
                        mod_id = "mod5",
                        name = "koppen_id5", 
                        unit_label = koppen_labs)
p6 <- plot_coef_varying(mod3, 
                        mod_id = "mod6",
                        name = "koppen_id5", 
                        unit_label = koppen_labs)
cowplot::plot_grid(p1, p2, p3, p4, p5, p6, nrow = 2)
```
